"""initial migration.....

Revision ID: 029d83fc41cc
Revises: 
Create Date: 2020-02-22 01:49:45.200985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029d83fc41cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    op.create_table('domain',
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.PrimaryKeyConstraint('domain_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('message',
    sa.Column('message_id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=True),
    sa.Column('domain_id', sa.String(length=12), nullable=True),
    sa.Column('src_ip', sa.String(length=16), nullable=True),
    sa.Column('ptr_record', sa.String(length=128), nullable=True),
    sa.Column('hdr_from', sa.String(length=256), nullable=True),
    sa.Column('env_from', sa.String(length=256), nullable=True),
    sa.Column('hdr_to', sa.String(length=256), nullable=True),
    sa.Column('dst_domain', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.account_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.domain_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_message_src_ip'), 'message', ['src_ip'], unique=False)
    op.create_table('attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('reason_extra', sa.String(length=256), nullable=True),
    sa.Column('delivered', sa.String(length=32), nullable=True),
    sa.Column('delivery_detail', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.message_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient')
    op.drop_table('attachment')
    op.drop_index(op.f('ix_message_src_ip'), table_name='message')
    op.drop_table('message')
    op.drop_table('domain')
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('account')
    # ### end Alembic commands ###
