"""empty message

Revision ID: 1f0ef92767aa
Revises: 724ec56d6ea7
Create Date: 2020-02-16 21:53:01.292994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f0ef92767aa'
down_revision = '724ec56d6ea7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('account_id', sa.String(length=12), nullable=True),
    sa.Column('domain_id', sa.String(length=12), nullable=True),
    sa.Column('src_ip', sa.String(length=16), nullable=True),
    sa.Column('ptr_record', sa.String(length=128), nullable=True),
    sa.Column('hdr_from', sa.String(length=256), nullable=True),
    sa.Column('env_from', sa.String(length=256), nullable=True),
    sa.Column('hdr_to', sa.String(length=256), nullable=True),
    sa.Column('dst_domain', sa.String(length=128), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('timestamp', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_src_ip'), 'message', ['src_ip'], unique=False)
    op.create_table('recipient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('reason_extra', sa.String(length=256), nullable=True),
    sa.Column('delivered', sa.String(length=32), nullable=True),
    sa.Column('delivery_detail', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipient')
    op.drop_index(op.f('ix_message_src_ip'), table_name='message')
    op.drop_table('message')
    op.drop_table('domain')
    op.drop_table('account')
    # ### end Alembic commands ###
