"""Domain.name unique

Revision ID: 70adf71fa8f3
Revises: c2f800596200
Create Date: 2020-02-22 00:48:34.881670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70adf71fa8f3'
down_revision = 'c2f800596200'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'domain', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='unique')
    # ### end Alembic commands ###
