"""Account name unique

Revision ID: 71c1a83827ab
Revises: 70adf71fa8f3
Create Date: 2020-02-22 01:18:22.241038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c1a83827ab'
down_revision = '70adf71fa8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['name'])
    op.create_unique_constraint(None, 'domain', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'domain', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
